
export const COUNTRIES2: any[] = [
  {
    id: 1,
    title: 'Ejemplo 1',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-08-19',
    timeRegister: 6,
    status: 1,
  },
  {
    id: 2,
    title: 'Ejemplo 2',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-10',
    timeRegister: 5,
    status: 3,
  },
  {
    id: 3,
    title: 'Ejemplo 3',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-02-05',
    timeRegister: 5,
    status: 2,
  },
  {
    id: 4,
    title: 'Ejemplo 4',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-05-01',
    timeRegister: 4,
    status: 2,
  },
  {
    id: 5,
    title: 'Ejemplo 5',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-06-04',
    timeRegister: 4,
    status: 3,
  },
  {
    id: 6,
    title: 'Ejemplo 6',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-24',
    timeRegister: 3,
    status: 1,
  },
  {
    id: 6,
    title: 'Ejemplo 7',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-24',
    timeRegister: 3,
    status: 1,
  },
  {
    id: 6,
    title: 'Ejemplo 8',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-24',
    timeRegister: 3,
    status: 1,
  },
  {
    id: 6,
    title: 'Ejemplo 9',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-24',
    timeRegister: 3,
    status: 1,
  },
  {
    id: 6,
    title: 'Ejemplo 10',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-24',
    timeRegister: 3,
    status: 1,
  },
  {
    id: 6,
    title: 'Ejemplo 11',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-24',
    timeRegister: 3,
    status: 1,
  },
  {
    id: 6,
    title: 'Ejemplo 12',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-24',
    timeRegister: 3,
    status: 1,
  },
  {
    id: 6,
    title: 'Ejemplo 13',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-24',
    timeRegister: 3,
    status: 1,
  },
  {
    id: 6,
    title: 'Ejemplo 14',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-24',
    timeRegister: 3,
    status: 1,
  },
  {
    id: 6,
    title: 'Ejemplo 15',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-24',
    timeRegister: 3,
    status: 1,
  },
  {
    id: 6,
    title: 'Ejemplo 16',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-24',
    timeRegister: 3,
    status: 1,
  },
  {
    id: 6,
    title: 'Ejemplo 17',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-24',
    timeRegister: 3,
    status: 1,
  },
  {
    id: 6,
    title: 'Ejemplo 18',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-24',
    timeRegister: 3,
    status: 1,
  },
  {
    id: 6,
    title: 'Ejemplo 19',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-24',
    timeRegister: 3,
    status: 1,
  },
  {
    id: 6,
    title: 'Ejemplo 20',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-24',
    timeRegister: 3,
    status: 1,
  },
];
