/* Teacher Home */
export const studentList: any[] = [
  {
   /* idStudent */ idStudent: 1,
   /* enrollmente (matricula) */enrollment: 201900043,
   /* fullName-student */student: 'Katherine González',
   /* careerName (Nombre del grupo)*/group: 'IS61-Software' ,
   /* fullName-advisor */ advisor: 'Isay Gonzales', 
   /* fullName-company (Nombre de la empresa) */ company: 'Wayaweb',
   /* time-register (Tiempo total trabajado) */totalWork: 6,
  },
  {
    idStudent: 2,
    enrollment: 201900075,
    student: 'Katherine González',
    group: 'IS61-Software' ,
    advisor: 'Isay Gonzales', 
    company: 'Wayaweb',
    totalWork: 6,
  },
  {
    idStudent: 3,
    enrollment: 201900071,
    student: 'Katherine González',
    group: 'IS61-Software' ,
    advisor: 'Isay Gonzales', 
    company: 'Wayaweb',
    totalWork: 112,
  },
  {
    idStudent: 4,
    enrollment: 201900051,
    student: 'Katherine González',
    group: 'IS61-Software' ,
    advisor: 'Isay Gonzales', 
    company: 'Wayaweb',
    totalWork: 6,
  },
  {
    idStudent: 5,
    enrollment: 201900065,
    student: 'Katherine González',
    group: 'IS61-Software' ,
    advisor: 'Isay Gonzales', 
    company: 'Wayaweb',
    totalWork: 92,
  },
  {
    idStudent: 6,
    enrollment: 201900075,
    student: 'Katherine González',
    group: 'IS61-Software' ,
    advisor: 'Isay Gonzales', 
    company: 'Wayaweb',
    totalWork: 6,
  },
  {
    idStudent: 1,
    enrollment: 201900075,
    student: 'Katherine González',
    group: 'IS61-Software' ,
    advisor: 'Isay Gonzales', 
    company: 'Wayaweb',
    totalWork: 34,
  },
  {
    idStudent: 7,
    enrollment: 201900075,
    student: 'Katherine González',
    group: 'IS61-Software' ,
    advisor: 'Isay Gonzales', 
    company: 'Wayaweb',
    totalWork: 6,
  },
  {
    idStudent: 8,
    enrollment: 201900075,
    student: 'Katherine González',
    group: 'IS61-Software' ,
    advisor: 'Isay Gonzales', 
    company: 'Wayaweb',
    totalWork: 6,
  },
  {
    idStudent: 9,
    enrollment: 201900075,
    student: 'Katherine González',
    group: 'IS61-Software' ,
    advisor: 'Isay Gonzales', 
    company: 'Wayaweb',
    totalWork: 66,
  },
  {
    idStudent: 10,
    enrollment: 201900075,
    student: 'Katherine González',
    group: 'IS61-Software' ,
    advisor: 'Isay Gonzales', 
    company: 'Wayaweb',
    totalWork: 42,
  },
  {
    idStudent: 11,
    enrollment: 201900075,
    student: 'Katherine González',
    group: 'IS61-Software' ,
    advisor: 'Isay Gonzales', 
    company: 'Wayaweb',
    totalWork: 60,
  },
];
