/* Teacher Home */
export const studentTasks: any[] = [
  {
    id: 1,
    title: 'Primera tarea que se realizó',
    idStudent: 1,
    student: 'Katherine González',
    company: 'Wayaweb',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-08-19',
    timeRegister: 6,
    status: 1,
  },
  {
    id: 2,
    title: 'Se agregaron algunos detalles',
    idStudent: 1,
    student: 'Katherine González',
    company: 'Wayaweb',
    idProject: 1,
    nameProject: 'Vapemex',
    dateRegister: '2021-09-10',
    timeRegister: 5,
    status: 3,
  },
  {
    id: 3,
    title: 'La parte del front esta casi lista',
    idStudent: 1,
    student: 'Katherine González',
    company: 'Wayaweb',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-02-05',
    timeRegister: 5,
    status: 2,
  },
  {
    id: 4,
    title: 'La base de datos se ha completado',
    idStudent: 1,
    student: 'Katherine González',
    company: 'Wayaweb',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-05-01',
    timeRegister: 4,
    status: 2,
  },
  {
    id: 5,
    title: 'Faltan algunos detalles visuales',
    idStudent: 1,
    student: 'Katherine González',
    company: 'Wayaweb',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-06-04',
    timeRegister: 4,
    status: 3,
  },
  {
    id: 6,
    title: 'Se completo el apartado de registro',
    idStudent: 1,
    student: 'Katherine González',
    company: 'Wayaweb',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-24',
    timeRegister: 3,
    status: 1,
  },
  {
    id: 7,
    title: 'Los detalles fueron corregidos',
    idStudent: 1,
    student: 'Katherine González',
    company: 'Wayaweb',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-07-08',
    timeRegister: 6,
    status: 1,
  },
  {
    id: 8,
    title: 'Practicamente ya está lista la aplicación',
    idStudent: 1,
    student: 'Katherine González',
    company: 'Wayaweb',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-05-12',
    timeRegister: 4,
    status: 1,
  },
  {
    id: 9,
    title: 'Faltan algunos detalles visuales',
    idStudent: 1,
    student: 'Katherine González',
    company: 'Wayaweb',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-06-04',
    timeRegister: 4,
    status: 3,
  },
  {
    id: 10,
    title: 'Se completo el apartado de registro',
    idStudent: 1,
    student: 'Katherine González',
    company: 'Wayaweb',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-09-24',
    timeRegister: 3,
    status: 1,
  },
  {
    id: 11,
    title: 'Los detalles fueron corregidos',
    idStudent: 1,
    student: 'Katherine González',
    company: 'Wayaweb',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-07-08',
    timeRegister: 6,
    status: 1,
  },
  {
    id: 12,
    title: 'Practicamente ya está lista la aplicación',
    idStudent: 1,
    student: 'Katherine González',
    company: 'Wayaweb',
    idProject: 1,
    nameProject: 'AmmaClub',
    dateRegister: '2021-05-12',
    timeRegister: 4,
    status: 1,
  },
];
